name: deploy-frontend
on:
  workflow_dispatch: # запуск лише з UI

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  BUILD_DIR: dist # змінй, якщо 'build'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.FRONTEND_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: aws s3 sync "dist/" "s3://invest-spa-bucket/" --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" --paths "/*"
